### ISSUE TITLE
Where's the CI?

### ISSUE THREAD

**Issue by hsluoyz** [davideicardi/DynamicExpresso#120]
I only found Azure Pipelines badge in README, but it's only an image to: https://camo.githubusercontent.com/253ed46799c2081cfcbfe472ca04792697295748/68747470733a2f2f6461766964656963617264692e76697375616c73747564696f2e636f6d2f5f617069732f7075626c69632f6275696c642f646566696e6974696f6e732f64366664303030322d366435312d343137622d393238652d3237353931333739646663342f342f6261646765

Can we have a CI like Travis CI or AppVeyor or a working Azure Pipelines?

**Comment by davideicardi** [comment]
It wasn't a fake badge :smile:  ... but you are right that it doesn't point to the correct link (also because the project was private before, now it should be available as read only to all):
[![Build Status](https://public-davideicardi.visualstudio.com/dynamic-expresso/_apis/build/status/dynamic-expresso-CI?branchName=master)](https://public-davideicardi.visualstudio.com/dynamic-expresso/_build/latest?definitionId=4&branchName=master)

**Comment by hsluoyz** [comment]
@davideicardi the URL is broken (404) again:

![image](https://user-images.githubusercontent.com/3787410/84376768-306d1500-ac14-11ea-969f-925e074747c3.png)

**Comment by davideicardi** [comment]
Sorry you are right.

I don't know why but the old link 
https://public-davideicardi.visualstudio.com/dynamic-expresso/_build/latest?definitionId=4&branchName=master

doesn't work anymore. I will change it to

https://public-davideicardi.visualstudio.com/dynamic-expresso/_build?definitionId=4

thanks
davide
