### ISSUE TITLE
Concatenation of two strings is failing when used with latest EntityFramework Core

### ISSUE THREAD

**Issue by Rebel028** [davideicardi/DynamicExpresso#151]
We've faced an issue while using `Interpreter` with a latest (5.0.6) EF Core. 

`Parser` is using `String.Concat(Object, Object)` method to concatenate two objects as strings. Unfortunately it could not be translated to SQL by EF Core and since version 3.1 it will throw an exception as Linq queries are no longer evaluated on client.

Instead of using  `String.Concat(Object, Object)` it would be better to use `String.Concat(String, String)` explicitly. 

First of all, it will make things made in #58  work, and additionally it will be able to use generated expression with Linq to Entities as EF Core can correctly translate `String.Concat(String, String)` to SQL

**Comment by Rebel028** [comment]
Hello @davideicardi! 

Any updates on this issue?

**Comment by davideicardi** [comment]
@Rebel028 Sorry, quite busy in these days. I answered now with some considerations.
Unfortunately the change seems small but is is potentially dangerous. So i want to be sure that everything works.

If you need it now consider that you can easily create a local package and use that instead of the official one for now, or otherwise I can consider creating an unstable version for you.
