### ISSUE TITLE
Localizable Error Messages

### ISSUE THREAD

**Issue by Raphael-Saldanha** [davideicardi/DynamicExpresso#36]
It would be nice if it was possible to replace error messages. My system is used in several languages and i need to show all error messages in user's language.

The simplest solution is to change ErrorMessages from internal to public and remove const modifier from error messages.

But it would be nice if we have a mechanism to inject error messages or a Abstract Factory that creates ErrorMessages based on some conditions.

**Comment by davideicardi** [comment]
Yes, it can be a future enhancement.

For the solution I think that the most easy way is to use localized .NET resource files: [How to: Create a Localized Version of a Resource File](https://msdn.microsoft.com/en-us/library/vstudio/aa992030(v=vs.100).aspx). So instead of having a ErrorMessages class we should have a ErrorMessages resource file.

Of course any help is appreciated :wink:

**Comment by SaldanhaBR** [comment]
I will provide a possible solution soon.

**Comment by davideicardi** [comment]
Fixed, thanks to @jasonhumberstone
