### ISSUE TITLE
Operator ?: seams to evaluate both sides of expression.

### ISSUE THREAD

**Issue by 1andy11** [davideicardi/DynamicExpresso#44]
Expression
xx == null ? 0 : xx.SomeProperty
failed with exception "No property or field `SomeProperty` exists in type `Object` (at index 22)."
The problem is that the expression xx is null.
If I change the expression to "xx == null ? 1 : 2" it is evaluated and the result is 1.

**Comment by davideicardi** [comment]
Can you send me a full sample?
The error message seems to tell that the object doesn't have this method. Why the type is "object"? I expect to see some custom class.

thanks

**Comment by 1andy11** [comment]
Variable xx is null and that is why I suppose that the right part of the expression should not be evaluated, but it does. xx is really null because the result of the expression "xx == null ? 1 : 2" is 1.

**Comment by 1andy11** [comment]
Is there any progress with the problem?

**Comment by davideicardi** [comment]
I suspect that the problem is different.
Consider the expression `true ? 4/2 : 4/0` . If what you say was true this expression should throw an `Divide by zero` exception. But it correctly returns 2.

I suspect that you pass for `xx` a null object without specifying the type and so Dynamic Expresso doesn't known how to parse the expression.

Can you send me your full code to reproduce the problem.

**Comment by 1andy11** [comment]
OK
interpreter.SetVariable("xx", null);
interpreter.Eval("xx == null ? 0 : xx.SomeProperty");

The problem is probably that I use Variable.

**Comment by RupertAvery** [comment]
The problem is that the parser has no idea what xx is. You are assigning a null value to xx, and without any type information any parser cannot know what xx is. This is why C# forbids assigning a null value using the var expression.

So you need to pass in the type information explicitly using the SetVariable(string, object, Type) overload. Suppose you have SomeClass with SomeProperty:

{code}
interpreter.SetVariable("xx", xx, typeof(SomeClass));
{code}

Note that this does not work:

{code}
SomeClass xx = null;
interpreter.SetVariable("xx", xx);
{code}

Since the runtime passes a null object (without type information) into SetVariable, it acts as if it had no type at all, hence the need for an overload explicitly allowing you to set the type.

**Comment by 1andy11** [comment]
You are right.
Using SetVariable with type parameter make it work.
Thanks.
