### ISSUE TITLE
Is their any potential risk?

### ISSUE THREAD

**Issue by kuul13** [davideicardi/DynamicExpresso#45]
This is an excellent piece of work David. Impressed by the quality of this code. Do you think using Eval is dangerous in terms of security of the system/codebase/data? Can I send a piece of code that would may be delete the database/file/add a virus or give any flexibility to the user to pass some malicious code?

**Comment by davideicardi** [comment]
Thank you for your comment.

About the security see this section in the readme file: https://github.com/davideicardi/DynamicExpresso#security

I think that if configured correctly Dynamic Expresso is secure, because user are able to do only what you allow him to do. Or at least I'm not aware of any risks.
