### ISSUE TITLE
Parse a string, replacing only known variables?

### ISSUE THREAD

**Issue by LostSoulfly** [davideicardi/DynamicExpresso#77]
I would like to read a sort of template from a file and use that template to generate a string.

So,

`
public static string prefix = "[DateTime.Now.ToString(\"HH:mm:ss\") INFO]";
`

Would parse out to

`
[20:37:48 INFO]
`

But I can't figure out how to ignore the unidentified pieces. Is there a way with DynamicExpresso? Or is there an easier/more performant way?

**Comment by RupertAvery** [comment]
Let's take a look at that string:

`"[DateTime.Now.ToString(\"HH:mm:ss\") INFO]"`

The problem here is you want to have this work as a template, but you are mixing an expression with a string literal. These are intended for two different purposes.

If you want to template something, think of it as any other template file where you replace a token with something else. What you want to do is very much like binding, such as what happens in an HTML template such as in angular, or any other framework out there.

Consider the code:

`string.Format("[{0} INFO]", DateTime.Now.ToString("HH:mm:ss"))`

The string "[{0} INFO]" is tokenized. It presents a way of embedding information of a token `0` to be replaced inside a string that is meant for display consumption.

The `Format` function parses the string, looks for tokens and replaces them.

Dynamic Expresso does the job of evaluating an expression stored in a string, but you're mixing a code expression with a string literal. You're trying to mix two functionalities here: binding and evaluating. 

So let's write our own simple binder.  You get to implement the Evaluate method as needed:

`
string prefix = "[{{DateTime.Now.ToString(\"HH:mm:ss\")}} INFO]";

Regex curlybinding = new Regex("{{(.*?)}}");
var result = curlybinding.Replace(prefix, (match)=> {
 return Evaluate(match.Groups[1].Value);
});
`

`prefix` is now a tokenized string that contains an embedded expression.

The catch here is that your expression can't contain double curly braces, but this is rarely the case in normal code. Note that this will match multiple instances of tokenized expressions in your template string.

This is the method I used to create a bindable templating framework.

**Comment by davideicardi** [comment]
I agree with @RupertAvery, the best solution is to identify what need to be evaluated inside the template.

There is a feature inside Dynamic Expresso that can be used to detect which identifiers are used (returning a list of know and unknown identifiers), see [Identifiers Detection](https://github.com/davideicardi/DynamicExpresso#identifiers-detection). But this doesn't solve your problem, and this is not always 100% accurate.

If possible I suggest to change the template format as @RupertAvery as described, or in a similar way.
