### ISSUE TITLE
Target framework 4.5.2 in 2.x versions

### ISSUE THREAD

**Issue by JobaDiniz** [davideicardi/DynamicExpresso#79]
Why the sudden drop support for framework 4.5.2? I cannot install the new nuget in the a project targeting 4.5.2.

Was this intended?

**Comment by davideicardi** [comment]
Yes, I take the opportunity when converting to .net standard to also upgrade .net framework version.
I can probably also support .net 4.5, but I should check. For you is not possible to upgrade? Because nowdays there are a lot of packages that start to drop support for older frameworks.

Also note that for now v2 has only some bug fixes, there aren't new features, so you can also evaluate to continue to use v1.

**Comment by davideicardi** [comment]
Ok, I will try to add .net 4.5 support for the next release.

**Comment by moh-hassan** [comment]
@davideicardi 
I checked the package with Net45 and it's compiled without errors.
All test pass successfully in both net45 and netcoreapp2.0.

**Comment by davideicardi** [comment]
@moh-hassan If you are able to create a pull request I will be happy to merge it. Thanks

**Comment by moh-hassan** [comment]
PR is Done. 
[Check ](https://github.com/davideicardi/DynamicExpresso/pull/102)

**Comment by davideicardi** [comment]
Fixed with #102
